import 'dotenv/config'; import mongoose from 'mongoose'; import bcrypt from 'bcryptjs'; import { User, Product } from './models.js';
const products = [
 { name:'Aster Ceramic Lamp', category:'Home', price:84, rating:4.8, reviews:124, stock:18, featured:true, image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=85', description:'A warm, sculptural lamp with a hand-finished ceramic base and linen shade.' },
 { name:'Orbit Wireless Headphones', category:'Tech', price:219, rating:4.9, reviews:89, stock:12, featured:true, image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85', description:'Immersive sound, adaptive noise control, and all-day comfort in a clean silhouette.' },
 { name:'Kanso Everyday Tote', category:'Accessories', price:128, rating:4.7, reviews:61, stock:24, featured:true, image:'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=85', description:'A roomy vegetable-tanned leather tote designed for workdays and weekends.' },
 { name:'Mori Linen Set', category:'Apparel', price:96, rating:4.6, reviews:44, stock:30, image:'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=900&q=85', description:'Breathable, relaxed linen essentials in a soft mineral palette.' },
 { name:'Field Notes Journal', category:'Stationery', price:24, rating:4.9, reviews:203, stock:45, image:'https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=900&q=85', description:'Thoughtful paper goods for capturing ideas, plans, and small observations.' },
 { name:'Sol Glass Carafe', category:'Home', price:42, rating:4.5, reviews:35, stock:9, image:'https://images.unsplash.com/photo-1610824352934-c10d87b700cc?auto=format&fit=crop&w=900&q=85', description:'A considered glass carafe that turns everyday hydration into a ritual.' }
];
await mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/lumina-commerce'); await Product.deleteMany({}); await Product.insertMany(products); const password = await bcrypt.hash('Admin123!', 10); await User.findOneAndUpdate({ email:'admin@lumina.store' }, { name:'Lumina Admin', email:'admin@lumina.store', password, role:'admin' }, { upsert:true, new:true }); console.log('Seed complete. Admin: admin@lumina.store / Admin123!'); await mongoose.disconnect();
